### ISSUE TITLE
Sidebar tree navigation

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#128]
There's much that is common with #122 here as a tree can be thought of as a nested list in a way.

ST3 (at the time of writing this at least) *just* supports showing a filtered file system view, but an oft requested feature is to have a sidebar api to allow functionality like a namespace/class browser and to display other hierarchical information.

We should design to allow this wider abstraction from the start.

**Comment by zoli** [comment]
moved to backend repo https://github.com/limetext/backend/issues/107.
