### ISSUE TITLE
I'd like to help

### ISSUE THREAD

**Issue by gwilymgj** [limetext/lime#174]
Hi - I know this isn't the place for this sort of thing, but I couldn't find another way to contact you. I'd like to help, but I'm no Python guru. PHP based web dev is my thing.

I'd like to help with the website, acting as a contact point for enquiries (to shield developers), writing documentation or managing a Kickstarter campaign to get Lime Text to production. Anything that I can do to see this happen basically.

Happy Christmas from the sunny South Pacific

:)

**Comment by FichteFoll** [comment]
I've been idling on the channel for all this time now, but it's pretty dead. I am still registered as the owner and I think I will remain for quite a while. If you'd like to do anything with it, just comment here or `/msg` me on freenode. I have a bouncer and am always there.

I doubt it'll happen though.
