### ISSUE TITLE
qml: hookup mouse input

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#201]
As of writing this, the text is rendered using a [qml listview](http://qt-project.org/doc/qt-5.0/qtquick/qml-qtquick2-listview.html), with each line of text being a separate qml item. Not sure if that complicates anything w.r.t. selecting a region that covers multiple lines with the mouse or not.

**Comment by zidoms** [comment]
Now we are catching most of mouse inputs if there is any problem left should be opened in a separate issue.
