### ISSUE TITLE
Finish backend/parser

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#209]
See https://github.com/limetext/lime/issues/141#issuecomment-28869255, https://github.com/limetext/lime/issues/141#issuecomment-28870741.

**Comment by quarnster** [comment]
This issue is too vague, but I'm not sure how to make it more concrete without actually implementing support for say libclang parsing of cpp files and [go/ast](http://golang.org/pkg/go/ast/) support for go files. The package should define one or more interfaces necessarily to *support* both of those uses (and any other language parser as possible), but not actually implement them (which should be done in a separate package or even repository).

**Comment by gwenzek** [comment]
[The doc quarnster  mentionned is now here](https://godoc.org/github.com/limetext/lime-backend/lib/parser)
[While the source is here](https://github.com/limetext/lime-backend/blob/master/lib/parser/parser.go)
