### ISSUE TITLE
log4go issue (was: QML frontend closes immediately)

### ISSUE THREAD

**Issue by bitdivision** [limetext/lime#260]
When running ./qml it closes immediately:

$ ./qml
Closing...

As far as I can see I followed the build instructions.

This seems to be the same issue as https://github.com/limetext/lime/issues/247 however I don't see any resolution there. Perhaps this is related to my pull request https://github.com/limetext/lime/pull/259?

Archlinux:

$ go version
go version go1.2 linux/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bitdivision/gocode"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"

$ uname -a
Linux elysium 3.13.5-1-ARCH #1 SMP PREEMPT Sun Feb 23 00:25:24 CET 2014 x86_64 GNU/Linux

**Comment by quarnster** [comment]
Closing issue here, moved to the log4go repo https://github.com/limetext/log4go/issues/1
