### ISSUE TITLE
Lime packages

### ISSUE THREAD

**Issue by zoli** [limetext/lime#283]
Shouldn't we move `*.tmbundle` files and `TextMate-Themes` to `backend\packages`? Aren't they coming with limetext on installation or sth like that?
Sublime doesn't use exact `*.tmbundle` it uses `*.sublime-package` which is simplified version of the `*.tmbundle` and its not organized inside like having Commands, Snippets and etc in separate folders will we go with `*.tmbundle`?
Personally i prefer TextMate bundles they are more complete and functional.

**Comment by quarnster** [comment]
Are there any concrete action items here? Let's make a checklist, if not lets close it

**Comment by zoli** [comment]
I'll make a checklist or milestone for supporting packages in [lime-backend](https://github.com/limetext/lime-backend).
At this step I'll try to implement same as sublime functionality based on documentations [here](http://docs.sublimetext.info/en/latest/extensibility/packages.html).
