### ISSUE TITLE
Right to left languages

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#295]
I remember requests for this showing up in the sublime text forums every now and then. The backend makes use of Go's unicode rune and string features, but I don't know if this is enough for right to left languages or if there's more to it than that.

Does it work already in the termbox and qml frontends? Is it just displayed left to right, or is it stored like that also? Does the [Region](http://godoc.org/github.com/quarnster/util/text#Region)'s `A` and `B` values make sense? How about the backspace key being bound to the "left_delete" command, does it work as expected with right to left languages?

@zoli, am I correct in that you can speak and write Farsi? Have you seen anything that is obviously broken with regards to supporting Farsi?

Not critical to solve for 0.1, but I would like to have it in 1.0 and if there are issues it's good to start discussing so that we have plenty of time to think of solutions :)

**Comment by zoli** [comment]
Movet to backend https://github.com/limetext/backend/issues/110.
