### ISSUE TITLE
frontend/qml: Just transform original View for minimap

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#301]
Right now the minimap is just the original view duplicated with a smaller font size. This means that it is doing all the same work twice. It'd be better if it was possible to simply have just a single LimeView component and we have another component with the [scale](http://qt-project.org/doc/qt-5/qml-qtquick-item.html#scale-prop) property set which then references the original component.

**Comment by erbridge** [comment]
Migrated to limetext/lime-qml#8.
