### ISSUE TITLE
Lime vs Atom

### ISSUE THREAD

**Issue by ilanbiala** [limetext/lime#304]
Since Atom is open-source by GitHub and has a tremendous amount of support, is there a reason to keep developing this project?

**Comment by kolmnurk** [comment]
Came here to say basically the same thing that leavengood said.For me it's a total dealbreaker that atom uses node.js. Most likely it will never be as fast as application written in C++, Go etc.  You shouldn't wait the code to appear on the screen while fast typing :)

**Comment by dmikam** [comment]
my 2 cents - Atom is slow, because of using web-based frontend and it is limited by it. Lime, potentialy could have any frontend (for example OpenGL based as i think it have Sublime) and could be much faster then Atom. One of the reasons people love Sublime is it's lightspeed fastness and lightweightness :D

**Comment by DMLou** [comment]
I'll say one this for Atom: its browser roots does allow for a lot of neat features like live preview of formatted documents (HTML, Markdown, Asciidoc, etc) within an editor tab.

Maybe this is something for a 2.0 version of Lime, but perhaps adding in some sort of browser engine as a "side car" just for live preview purposes would certainly be a good idea. It doesn't need to be done as part of the main editor, of course, but as an extended mode or plugin or something.

**Comment by pjoe** [comment]
Just my 2 cents:

If you like Atom ... well then use Atom :D

For me the interesting part of lime is the architecture making a solid split between frontend and backend and already having 3 different frontends in progress, that all makes sense:

* QML (which is actually rendered with OpenGL) for your standard desktop app
* Termbox for running in a terminal, which could even work over ssh (so you get kind of the same 'feature' as vim, in that it is usable for remote editing)
* HTML5 for that browser based 'editor in the cloud'

I have not seen any other editor with this level of ambition (in terms of covering frontend usecases).

I suppose you could probably argue that Atom could be hacked into doing something similar, but to me that would be exactly that: a hack that probably wouldn't perform very well.

**Comment by DMLou** [comment]
First, for the sake of full disclosure, I have been using Atom and I like it, but it's not like I like it so much I'm not willing to try/switch to something else. :) Lime has a lot of potential and I'm very interested in it as a result. :)

I have to agree that the architectural split in Lime does give it a lot of potential that other editors may not have. That split architecture, similar to what you said, may allow for adding an HTML5 preview mode as part of a front-end (or an additional front-end that can be loaded dynamically along with others). If that were to happen, you'd absolutely have the best of both worlds.

**Comment by bombless** [comment]
Will the termbox front-end work on Windows? :D
