### ISSUE TITLE
Increase awareness and attractiveness [$5 awarded]

### ISSUE THREAD

**Issue by gbbr** [limetext/lime#344]
I don't know about you guys. But to me it is of utmost essentiality what the IDE I am using looks like. I have a huge support and interest in all that is created using Go but please (pretty please?), use a better font and styling for the editor. Other than that - I think you're on the right track.

May I suggest the following fonts:  Consolas (used by GitHub), Monaco (classical coding font), Menlo (similar to IntelliJ IDEs)

Also, line-height seems a bit low, try increasing it a bit to increase readability and maybe replace the screenshots on Git and the homepage with the new ones and I can guarantee you that awareness and interest in this project will grow significantly.

I'll be glad to take a look if I get a chance too and possibly submit a PR with these changes.
##

**Comment by quarnster** [comment]
@gbbr https://www.bountysource.com/issues/4064784-increase-awareness-and-attractiveness/developers says:
```
zidom submitted a claim but the backer hasn't responded. 13 days ago

NOTE: This will be paid out if all backers accept this or if no backers reject this by Jan 12, 2015 8:04 PM (GMT). 
```

So unless you object it should go to @zidoms in a couple of hours. There might be a button for you to click to "ok" the change quicker though.

**Comment by gbbr** [comment]
:+1:
