### ISSUE TITLE
frontend/qml: runtime reload of qml files no longer works (crashing instead)

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#374]

**Comment by bawigga** [comment]
@quarnster Could you provide some more details and context on this? Would this make it so that a code change in a QML file would instantly reload in the currently running application?

**Comment by quarnster** [comment]
@bawigga:
> Would this make it so that a code change in a QML file would instantly reload in the currently running application?

If the qml frontend was running, it used to instantly reload the QML files (i.e. re-create the UI) when one of the qml frontend's QML files changed. IE no need to restart the app to see the changes. At some point that stopped working, resulting in a crash instead. Haven't looked into cause, or if it's still an issue.

See comments and code for [newEngine](https://github.com/limetext/lime/blob/8eaa815b4ba4dd284dc1b0d40f4047af4498622a/frontend/qml/main.go#L665) and the "[reload-loop](https://github.com/limetext/lime/blob/8eaa815b4ba4dd284dc1b0d40f4047af4498622a/frontend/qml/main.go#L770)" which IIRC pretty much covers the logic involved.

**Comment by erbridge** [comment]
Migrated to limetext/lime-qml#6.
