### ISSUE TITLE
getting error by building on Lubuntu VM

### ISSUE THREAD

**Issue by zigal** [limetext/lime#404]
Hey,

I've currently tried [this guide](https://github.com/limetext/lime/wiki/Ubuntu-13.10-(and-probably-others)-quickstart) for building lime under Lubuntu. But every time by the step ``go get github.com/limetext/lime/frontend/termbox`` or ``go build`` I get the following error message:

```
load cmd/cgo: package cmd/cgo: open /usr/src/cmd/cgo: no such file or directory
```

How I can fix this?

Regards,
@zigal

**Comment by erbridge** [comment]
If this is still an issue, please reopen in [limetext/support](https://github.com/limetext/support).
