### ISSUE TITLE
travis: Multi-os build

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#418]
One needs to specifically request it at the moment, but getting travis-validation on all OS's enabled would be good. 

http://docs.travis-ci.com/user/multi-os/

**Comment by meatballhat** [comment]
ahoy ahoy, you should be able to use `language: go` on OSX now :smiley:

**Comment by erbridge** [comment]
Thanks for the update @meatballhat.

**Comment by erbridge** [comment]
The `fix_ci_osx` branch has a working in progress for getting this going. It looks like there's an issue with installing `python3`, and `qml` isn't installed, yet.
