### ISSUE TITLE
Command: toggle_minimap

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#45]

**Comment by bawigga** [comment]
1. Menu Item: `View > Show/Hide Minimap` This is a global toggle and applies to all windows.
2. User Setting: Check the `"show_minimap": false` user setting. See [this stackoverflow answer](http://stackoverflow.com/a/15611907/105061)

@quarnster any more requirements or implementation details on this one?

**Comment by zoli** [comment]
@bawigga The setting option `"show_minimap"` is a different issue we should check that on startup.
The `toggle_minimap` command should go in [`backend/commands`](https://github.com/limetext/lime/tree/master/backend/commands) however for these type of commands which are impacting directly the frontend like `toggle_minimap`, `toggle_sidebar`(#93) and etc we need to expand Frontend interface and i think we should do it soon. 

But for now same as #472 we can implement this inside the qml frontend.

**Comment by bawigga** [comment]
Thanks @zoli. 

I'll add another issue to track the default settings functionality for `show_minimap`.

**Comment by quarnster** [comment]
@bawigga, @zoli, frontend interface doesn't need to change. This should be implemented as a command that toggles the "show_minimap" setting. The settings item will [notify](https://github.com/limetext/text/blob/c52812c8d01ff59ebd0925dbd4295d0fdd61136d/settings.go#L130) all [OnChangeCallback](http://godoc.org/github.com/limetext/text#OnChangeCallback)s that a setting [changed](https://github.com/limetext/text/blob/c52812c8d01ff59ebd0925dbd4295d0fdd61136d/settings.go#L118), so the frontend only needs add a callback via [AddOnChange](http://godoc.org/github.com/limetext/text#Settings.AddOnChange) that specifically deals with "show_minimap" or just check for "show_minimap" in an existing callback.

**Comment by zoli** [comment]
@quarnster how about commands like `show_overlay` #41 or auto completions these should be done over settings to?

**Comment by quarnster** [comment]
@zoli Only if it makes sense :)

show_overlay and auto completions are both more complex than various "toggle_"-commands so I wouldn't think so, but I haven't given them much thought so maybe. If it makes things easier to implement, understand and maintain go for it, if not try to figure out what approach would.

That goes for everything, even existing code. If there's an easier, more understandable and maintainable way to do something, lets have a discussion and either change approach or document why the current approach is used over the other.

**Comment by zoli** [comment]
Using settings for "toggle_"-commands(#51 #93 #98 #99 #100) is much better IMO, Thinking about the `show_overlay` and [go-to](https://github.com/limetext/lime/issues?q=is%3Aopen+is%3Aissue+label%3Agoto) commands distracted me from the simple way of implemention "toggle_"-commands.

**Comment by erbridge** [comment]
Migrated to limetext/lime-backend#45.
