### ISSUE TITLE
panic: unsupported variant type: 1024 (QJSValue)

### ISSUE THREAD

**Issue by zoli** [limetext/lime#478]
This panic occurs on opening new file with qml frontend. Apparently there is a problem converting javascript object to `backend.Args` [here](https://github.com/limetext/lime/blob/master/frontend/qml/dialogs/OpenDialog.qml#L24).

**Comment by zidoms** [comment]
Related to https://github.com/go-qml/qml/issues/137.

**Comment by obscuren** [comment]
Wanted to let you know I've updated the above issue on the go-qml repo with a possible somewhat decent solution.

**Comment by erbridge** [comment]
Migrated to limetext/lime-qml#4.
