### ISSUE TITLE
qml dynamic status bar

### ISSUE THREAD

**Issue by zoli** [limetext/lime#486]
- [ ] Responding to `view.set_status`, `view.get_status`, `view.erase_status`
- [ ] Responding to `status_message`
- [ ] Showing tab size
- [ ] Showing the display syntax

**Comment by bawigga** [comment]
Some more info from @zoli in the gitter chat:

> for each view status bar we store statuses in a map here https://github.com/limetext/lime/blob/master/backend/view.go#L47 currently we can modify them by SetStatus, GetStatus and EraseStatus there should be a connection between setting status and front end which is not implemented yet

**Comment by zoli** [comment]
Implemented in termbox frontend via #508, Most of the code should be the same for qml frontend to.

**Comment by erbridge** [comment]
Migrated to limetext/lime-qml#3.
