### ISSUE TITLE
[build] on windows 7

### ISSUE THREAD

**Issue by AlexiaChen** [limetext/lime#493]
According to these descriptions related to : https://github.com/limetext/lime/wiki/Goals and https://github.com/limetext/lime/wiki/Building-on-Windows 

NB: gopy currently fails very badly on Windows, so do NOT expect to have working or even fully built code after following these instructions. We are working on solutions.

Cross platform (It appears to be compiling and running on OSX and Linux last I tried, but needs further validation.)

Does it mean that I cannot currently build limetext on windows 7? right?

And I wanna ask a couple of stupid questions:
Will it have installation package(like setup.exe file built from NSI Script) on windows in further future?
Will it have package  on Linux (like ubuntu or Arch .etc) comes with their official source in further future? so that i could kindly install this software without building source.

**Comment by quarnster** [comment]
>Will it have installation package(like setup.exe file built from NSI Script) on windows in further future?
If someone signs up to handle and maintain it.

>Will it have package on Linux (like ubuntu or Arch .etc) comes with their official source in further future?
If someone signs up to handle and maintain it.

#228 deals with all things windows, so closing as a dup.
