### ISSUE TITLE
Cursor bug in qml frontend

### ISSUE THREAD

**Issue by zguangyu** [limetext/lime#496]
![2015-02-17 10 38 28](https://cloud.githubusercontent.com/assets/551369/6222575/4b8e48c8-b691-11e4-9002-fae2379d0c75.png)

You can see there are 6 cursors in the editor. When I click the text, a new cursor is created, and the others keep unchanged.

EDIT:
Sorry, I forgot to mention how to reproduce it. You need to hold Cmd and click the text. I don't think we need such a feature.

**Comment by zguangyu0000** [comment]
The indentation in the minimap also seems wrong. But it's correct in the screenshot of README.md.

**Comment by zguangyu** [comment]
Sorry, but I forgot how to reproduce it. :(

**Comment by zidoms** [comment]
Actually holding CMD or CTRL and clicking should add +1 cursor without removing other cursors, multiple cursors/selections is one of [sublime text](http://www.sublimetext.com) features.

**Comment by FichteFoll** [comment]
lime would die for me if multiple selections were removed :smile:
