### ISSUE TITLE
SetActiveView method name

### ISSUE THREAD

**Issue by zoli** [limetext/lime#521]
From what I see in sublime text api there is `focus_view(view)` method on `sublime.Window` class, but we have `SetActiveView` method and it's not exported yet is there any reason behind the naming? Should we go and rename it to `FocusView` and export it to python api or just make a `fucos_view` function in [`window_manual.go`](https://github.com/limetext/lime/blob/master/backend/sublime/window_manual.go) which runs `SetActiveView`?

**Comment by quarnster** [comment]
IMO I'd prefer to keep it named `SetActiveView` as it's the counter part of `ActiveView` and consistent with general Go function naming, and then just export it as "focus_view".

**Comment by zoli** [comment]
Closed via b6ada4f4f43ea32a0dde5a4866b2a400bec14e6a kept the `SetActiveView` name.
