### ISSUE TITLE
New frontend based on gxui

### ISSUE THREAD

**Issue by fcantournet** [limetext/lime#524]
Go now has a (possibly serious) native UI library (in alpha) named gxui.
It isn't backed by Google at the moment, but it has some traction and more potential then previous attemps imo

Considering the backend of limetext is in go, and one of the objective is fast, responsive UI, wouldn't it make sense to build a frontend based off gxui ?

**Comment by crr0004** [comment]
This project definitely needs a native ui that is going to quick. The qml is decent however I have noticed some rendering glitches. I'll be all for supporting a go native ui front end

**Comment by lunny** [comment]
+1

**Comment by erbridge** [comment]
If anyone wants to start work on this, please go ahead. It sounds interesting.

**Comment by crr0004** [comment]
I am starting to work on this. gxui has next to no documentation so I'm going to attempt to assist with that while I'm at it

**Comment by trishume** [comment]
I'm not sure gxui has all the functionality necessary for a nice text editor front-end. For example I took a quick look through the source and I don't think it has the ability to do subpixel font rendering, so text will look way crappier than normal. I'm also not sure it supports retina displays.

QML has had an absurd amount of work put into it and is pretty great, if there are issues with the QML interface that's not QML's fault. I've looked through the code of lime-qml and it does some pretty inefficient things (all text is rich text for example, so goes through an HTML parser and expensive layout). It would probably take much less work to improve the QML front-end to excellence than to write a passable gxui one.

**Comment by fcantournet** [comment]
@trishume I agree 100%.
I suggested this out of sheer enthusiasm for the new gxui effort, but it is not on par feature-wise with QML.
This was a false good idea. We should close this unless someone has made significant headway in this direction.

**Comment by db47h** [comment]
One thing gxui has going for it is BSD license, vs go-QML's LGPL (no troll intended). As far as I understand the LGPL, it does not have much of an impact if the library is linked dynamically, but go-qml being linked statically, what's the license of the resulting binary?

Anyhow, the gxui API is still changing and although implementing a text-editor "widget" for it right now may seem a bit premature, it could help both projects.

**Comment by ricochet1k** [comment]
Quote from gxui: 

> Unfortunately due to a shortage of hours in a day, GXUI is no longer maintained.

**Comment by erbridge** [comment]
Closing, since `gxui` is unmaintained.
