### ISSUE TITLE
termbox frontend: log messages missing, nil pointer dereference

### ISSUE THREAD

**Issue by pwaller** [limetext/lime#526]
I just tried to get up and running on Ubuntu Vivid (15.04).

This panics due to `scheme` being `nil`.

https://github.com/limetext/lime/blob/master/frontend/termbox/main.go#L764

It became apparent that the reason is because the themes didn't load.

https://github.com/limetext/lime/blob/master/frontend/termbox/main.go#L167

However, there is no log in the console, I had to figure this out by reading the code. I tried logging with `log.Debug/Warn/Error` and even using the standard library `log` package, but I couldn't get anything printed.

How do I instrument the code with log messages?

**Comment by quarnster** [comment]
> How do I instrument the code with log messages?

For the termbox backend it should dump to the file `debug.log`, but the console can be enabled via commandline parameter `-console`.
