### ISSUE TITLE
go run main.go throws error

### ISSUE THREAD

**Issue by farhaanbukhsh** [limetext/lime#541]
go run main.go throws error:

./main.go:25: undefined: qmlfrontend
./main.go:41: undefined: qmlfrontend

Work around : 
go run main.go qml_frontend.go frontend_window.go frontend_view.go qml_dialog.go keys.go

All the files need to be compiled and run

**Comment by quarnster** [comment]
Issue fails to satisfy [Contributing#1](https://github.com/limetext/lime/blob/master/CONTRIBUTING.md#1-the-issues-list-is-for-development-purposes-only):
>All issues reported here should result in code being changed, added and/or removed.

**Comment by erbridge** [comment]
To solve your issue, you should be doing a `go build`.
