### ISSUE TITLE
Error while trying to build Lime Text : termbox compilation fail

### ISSUE THREAD

**Issue by gbersac** [limetext/lime#543]
I am in the process to install Lime text on ubuntu 14.04 using this totorial : https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04
When I try to run the command :

```shell
go get -u github.com/limetext/lime/frontend/termbox
```

I get the following error message :

```
# github.com/limetext/lime/frontend/termbox
../termbox/main.go:514: syntax error: unexpected range, expecting {
../termbox/main.go:517: syntax error: unexpected }
../termbox/main.go:592: syntax error: unexpected range, expecting {
../termbox/main.go:595: syntax error: argument to go/defer must be function call
../termbox/main.go:600: non-declaration statement outside function body
../termbox/main.go:605: non-declaration statement outside function body
../termbox/main.go:632: non-declaration statement outside function body
../termbox/main.go:633: syntax error: unexpected }
```

**Comment by gbersac** [comment]
I just read the [contributing guideline](https://github.com/limetext/lime/blob/master/CONTRIBUTING.md) and I understood this ticket doesn't belong here. Sorry, I'll know it for the next time ^^

**Comment by FichteFoll** [comment]
So yeah, I have zero experience with writing or running Go code since I only follow this repo, but I suggest you to check your Go version.

**Comment by erbridge** [comment]
You need go 1.4 or later. The syntax changed in that version.

**Comment by gbersac** [comment]
That's right ! I installed go using :

```
sudo apt-get install golang
```

But the repository is outdated. I should consider moving to arch linux ^^

**Comment by erbridge** [comment]
Try [gvm](https://github.com/moovweb/gvm).
