### ISSUE TITLE
Godoc links on wiki page for `Implementing commands` are broken

### ISSUE THREAD

**Issue by axiomabsolute** [limetext/lime#549]
The Godoc links on the (Implementing commands)[https://github.com/limetext/lime/wiki/Implementing-commands] Wiki page return 404 Not Found.  This appears to be due to a mis-formatting of the URL caused by restructuring the project.

Before (broken): `http://godoc.org/github.com/limetext/lime/backend#TextCommand`

After (correct): `http://godoc.org/github.com/limetext/lime-backend/lib#TextCommand`

**Comment by axiomabsolute** [comment]
Fixed GoDoc links on the wiki page mentioned, as well as a link to the `commands` directory in the lime-backend repo.

**Comment by erbridge** [comment]
Looks like you've fixed this. No need to open an issue in future. Just go in and make the changes.
