### ISSUE TITLE
Outdated Instructions in the Ubuntu building guide page

### ISSUE THREAD

**Issue by aki237** [limetext/lime#550]
When I ran the commands like
```go get -u github.com/limetext/lime/frontend/termbox  ```
It showed up some errors
```
package github.com/limetext/lime/frontend/termbox
	imports github.com/limetext/lime/frontend/termbox
	imports github.com/limetext/lime/frontend/termbox: cannot find package "github.com/limetext/lime/frontend/termbox" in any of:
	/usr/local/go/src/github.com/limetext/lime/frontend/termbox (from $GOROOT)
	/home/user/golang/src/github.com/limetext/lime/frontend/termbox (from $GOPATH)
```

I think the link has to be like
```go get github.com/limetext/lime-termbox/main```
[Link to the wiki page](https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04)

**Comment by FichteFoll** [comment]
See https://github.com/limetext/lime/issues/549

**Comment by erbridge** [comment]
Yup. Please go and fix the wiki if it's wrong :).

**Comment by aki237** [comment]
Fixed the wiki page of Ubuntu 14.04. Check that out.....
[Ubuntu Wiki](https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04)

**Comment by funnylookinhat** [comment]
Just a heads up - the guide is missing requirements to have qt5 installed.  Otherwise, when you get to the QML step, it complains about not being able to find Qt5 from pkgconfig.

```
src/github.com/limetext/lime-qml/main$ go build
# pkg-config --cflags Qt5Core Qt5Widgets Qt5Quick
Package Qt5Core was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Core.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Core' found
Package Qt5Widgets was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Widgets.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Widgets' found
Package Qt5Quick was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5Quick.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5Quick' found
pkg-config: exit status 1
```

**Comment by aki237** [comment]
@funnylookinhat Now check out that link....
Added the Qt5 installation

**Comment by funnylookinhat** [comment]
Seems good.  Hitting a separate problem now - but that's because I'm on 15.04.  Documentation seems fixed.  Thanks!
