### ISSUE TITLE
limetext-termbox crashes on nix

### ISSUE THREAD

**Issue by Bevaz** [limetext/lime#551]
See issue NixOS/nixpkgs#9041

**Comment by quarnster** [comment]
You need to [init and update the git submodules](https://github.com/limetext/lime/wiki/Troubleshooting#it-builds-fine-but-crashes-when-i-try-to-start-it-with-a-log-message-like-093142-utc-20150804-eror-logloggererror5-unable-to-load-colorscheme-definition-open-packagesthemestextmate-themesmonokaitmtheme-no-such-file-or-directory).

(I have a vague memory that this was already somewhere in the wiki, but I couldn't find it so created a new entry).

BTW, it's not ready to be used for anything real so not sure packaging it up makes sense right now.
