### ISSUE TITLE
no buildable in ubuntu 14.04

### ISSUE THREAD

**Issue by octavioGarciaR** [limetext/lime#552]
Hi, I'm new in ubuntu and GitHub and I follow the steps in https://github.com/limetext/lime/wiki/Building-on-Ubuntu-14.04 but when I type the command:

go get github.com/limetext/lime-backend/lib/...

for get the backend my terminal shows me:

go build github.com/limetext/lime-backend/lib/render/textmate: no buildable Go source files in /root/golang/src/github.com/limetext/lime-backend/lib/render/textmate

and I thinks this can be a problem, please tell me what I'm doing wrong, I follow the steps in the above link and all goes well but in this step I'm stuck.

**Comment by zoli** [comment]
The termbox frontend is here https://github.com/limetext/lime-termbox

**Comment by octavioGarciaR** [comment]
thanks a lot zoli now I can using the termbox
