### ISSUE TITLE
Unable to get QML frontend on OSX

### ISSUE THREAD

**Issue by legate** [limetext/lime#553]
Hi, I am new to Lime Text and Qt. I am trying to get the QML frontend on OS X but run into this error:

    $ export PKG_CONFIG_PATH=$(brew --prefix python3)/Frameworks/Python.framework/Versions/3.4/lib/pkgconfig:$(brew --prefix qt5)/lib/pkgconfig:$(brew --prefix oniguruma)/lib/pkgconfig
    $ go get github.com/limetext/lime-qml/main/...
    # gopkg.in/qml.v1
    clang: error: unknown argument: '-framework\'
    clang: error: unknown argument: '-framework\'
    clang: error: unknown argument: '-framework\'
    clang: error: unknown argument: '-framework\'
    clang: error: unknown argument: '-framework\'
    clang: error: unknown argument: '-framework\'
    clang: error: no such file or directory: 'QtWidgets'
    clang: error: no such file or directory: 'QtQuick'
    clang: error: no such file or directory: 'QtGui'
    clang: error: no such file or directory: 'QtQml'
    clang: error: no such file or directory: 'QtNetwork'
    clang: error: no such file or directory: 'QtCore'

What am I doing wrong? Thanks.

**Comment by quarnster** [comment]
Brew messed up, you need to fix brews qt5 pkg-config files manually.

**Comment by quarnster** [comment]
Or qt messed up rather: https://github.com/Homebrew/homebrew/commit/6174f9b330a40c979d19e58c122cc277bc2f2e9e#diff-1fcd42cb0cbfc068ca2b4b3cdf0b1550
