### ISSUE TITLE
Is lime text dead ?

### ISSUE THREAD

**Issue by gbersac** [limetext/lime#554]
I feel like it is an awesome project ! Sublime text is not evolving anymore and atom is too slow. We need a total open source sublime text like lime text ! But no commit since april. Is it dead ?

**Comment by bredov** [comment]
As it is pointed out in README, this repo now turned to be a "meta-repo" and actual development is done in separate repos
> For the backend, please see limetext/lime-backend.
>
> There are also three frontends currently in development: limetext/lime-qml, limetext/lime-termbox, and limetext/lime-html.

**Comment by gbersac** [comment]
The link in the website "View our roadmap" button still link to this repo.
Still 17 day without any change...but still better, for sure.  I am still worried about the developpement of this project, but still better.

Carry on guys, this is a great and usefull project !

**Comment by zoli** [comment]
@gbersac Its not dead and as an open source project it relies on the spare time of contributors.

**Comment by gbersac** [comment]
Great to know ! I understand that finding time to code must be difficult. Carry on !

**Comment by quarnster** [comment]
It's not dead, just moving slowly. It'd move faster if more people helped out *hint* *hint* ;)

**Comment by gbersac** [comment]
I really considered contributing to limetext because it is an interesting project. The problem is : go. Not that it is a bad language, it is not, but I just don't like it. Very subjective. 

And I am 100% focused on rust. Sorry and good luck. I'm still interested in this project. I'll may create a rust plugin for lime ^^

**Comment by PSeitz** [comment]
I think go could be a problem since there is very limited number of developers available. With C++ e.g. most could start right away developing.

**Comment by grindhold** [comment]
@PSeitz I doubt that there are that few go-developers. I see the problem in lime's vast dependency hell. IMHO Go programs and libraries are meant to form their own independent eco-system. Dragging in dependencies from the C/C++-world is complicating enough. In this special case it's even Qt. Qt itself is its own ecosystem with everything from basic datatypes to a UI-library.
In a perfect world, Go would have a de-facto standard UI-toolkit and limetext would use that.
Just my two cents.

**Comment by jeremejevs** [comment]
Last commit in `limetext` org was made to `lime-backend` over 3 months ago. Not good =/
