### ISSUE TITLE
QML frontend build fails with "go build gopkg.in/qml.v1: g++: exec: "g++": executable file not found in $PATH"

### ISSUE THREAD

**Issue by shiriru** [limetext/lime#555]
Hello, I am not familiar with Go, neither QML, so I followed the instructions for building Limetext from source, but I got this:
`$ go build`
`$ go build gopkg.in/qml.v1: g++: exec: "g++": executable file not found in $PATH`
`pwd` is `~/src/github.com/limetext/lime-qml/main`
All env variables are set...
All dependencies are installed via `apt-get`
I am running amd64 3.16 kernel with elementary os distro.

Please, advice

**Comment by quarnster** [comment]
`apt-get install g++` perhaps? In either case, it's not ready for users yet but any help hacking on it is greatly appreciated
