### ISSUE TITLE
gxui instead qt?

### ISSUE THREAD

**Issue by kolkov** [limetext/lime#557]
What do you think about using gxui instead qt? Is it possible in the future?
https://github.com/google/gxui

**Comment by erbridge** [comment]
According to the readme, gxui is a dead project, sadly. It had promise.

**Comment by quarnster** [comment]
The backend is designed to be able to work with multiple frontends. If you'd like to work on a frontend using a specific UI library, then do it. There's not a lack of ideas on how to improve, just a lack of volunteers actually doing the work. (I don't see myself volunteering any time soon in case anyone is wondering)
