### ISSUE TITLE
Can't build following instructions: can't find sublime_plugin

### ISSUE THREAD

**Issue by yurivict** [limetext/lime#560]
It did build main executable in limetext/lime-qml/main, but this line fails:
```
m, err := py.Import("sublime_plugin")
```

Can you, instead of *writing up* instructions provide the shell script that does the same that you can run yourself and it succeeds?

Or alternatively, what is wrong? Where is this "sublime_plugin" supposed to come from?

**Comment by zoli** [comment]
I think this is fixed now, sublime_plugin [here](https://github.com/limetext/lime-qml/blob/master/main/sublime_plugin.py). Also if it is not fixed should be reopened in relevant repo
