### ISSUE TITLE
Unable to build: backend.View has no field or method Buffer

### ISSUE THREAD

**Issue by slgobinath** [limetext/lime#563]
Following the build instruction on Ubuntu 14.04_x64 bit with Go 1.5.3, Python 3.5.1. 
`go get github.com/limetext/lime-backend/lib/...` caused 

> go build github.com/limetext/lime-backend/lib/render/textmate: no buildable Go source files in /home/gobinath/.go/src/github.com/limetext/lime-backend/lib/render/textmate

and `go get github.com/limetext/lime-qml/main/...` terminates with errors like

> v.Buffer undefined (type *backend.View has no field or method Buffer, but does have backend.buffer)

**Comment by zoli** [comment]
lime-qml isn't still adapted with the latest merged pr https://github.com/limetext/lime-backend/pull/91 will be fixed soon, but the backend should be fine travis is passing for go 1.5

**Comment by zoli** [comment]
This is fixed now.
