### ISSUE TITLE
Unable to build on clean Ubuntu 16.04 with updated instructions

### ISSUE THREAD

**Issue by askalski** [limetext/lime#565]
I attempted to follow instructions from https://github.com/limetext/lime/wiki/Building-on-Ubuntu-16.04

here's my full output (limetext is a copy-and-paste of first script in that wiki page)

http://pastebin.com/mZjDAvwC

Any clues? Should I use some different version of go?
##

**Comment by ozra** [comment]
I got the same thing, following the same instructions, but for 15.10.
I'd reeeeally like to try lime out, since sublime is currently my fave editor, but way to closed source ;-) Impossible to mod that as I want.

**Comment by zoli** [comment]
I think this is a bug related to https://github.com/limetext/lime-qml, It seems that `w2.window` is `nil` on [frontend.go#L189](https://github.com/limetext/lime-qml/blob/master/main/frontend.go#L189).

**Comment by askalski** [comment]
ok zoli, can you tell me what version of go are you running with your Ubuntu 16.04 (and preferrably, where to get if from)? I would like to make my setup closer to yours.

**Comment by zoli** [comment]
@askalski My go version is `go1.6.2 linux/amd64`(with `export GODEBUG=cgocheck=0`) but I'm running on arch linux not ubuntu.

**Comment by askalski** [comment]
hmm, and could somebody try to actually use these instructions on bare ubuntu 16.04? I am sure I have the same version of go, and I followed all instructions very strictly.

**Comment by orangepick** [comment]
I was able to get a successful build using ubuntu 16.04 inside Docker 1.12 container (so bare install) and go version go1.6.2 linux/amd64. I did have to change 2 things in the build process
I had to add the following line : 
**go get github.com/limetext/sublime**   # added to resolve error
go get github.com/limetext/backend

I had to remove this line because it would error out each time with a missing file
 **go test github.com/limetext/backend/...**    # commented this line out

I was able to get a good build and limetext runs in a docker container (I have NOT tested extensively yet), but it works.

**Comment by edzob** [comment]
thanks for the "go get github.com/limetext/sublime" that fixed the backend error message I recieved on 16.04 when running the install script.

I now have only one error left, and when I do a google search on this github page I do not get any results so not sure how to find out what is causing this. Could you point me in the richt direction?

[08/20/16 10:39:33] [DEBG] Scanning testdata for packages
--- FAIL: TestWatchDir (0.10s)
        watcher_test.go:28: Expected package loaded
FAIL
FAIL    github.com/limetext/backend/packages    0.407s
ok      github.com/limetext/backend/parser      0.003s

**Comment by orangepick** [comment]
@edzob, I know it is NOT right, but I commented out the "go test ...." line for now to get a successful build.

**Comment by edzob** [comment]
ok.. I'll try that.  perhaps I can look at the test/code and see what TestWatchDir test is doing :)

**Comment by wishx** [comment]
With the wiki instructions as they are right now (Sept 20, 2016), I was able to build and run it without error on Linux Mint 18 (Ubuntu 16.04). Just letting folks know it's possible. :)

**Comment by zoli** [comment]
`TestWatchDir` is fixed by https://github.com/limetext/backend/commit/a33607b7d314f20ea9553c9422b3e87195827249.
