### ISSUE TITLE
Provide Homebrew recipe for easier install on macOS

### ISSUE THREAD

**Issue by kenorb** [limetext/lime#569]
I'd like to see the installation process on macOS like:

    brew install limetext

What needs to happen?

Is it new formula in [homebrew-cask](https://github.com/caskroom/homebrew-cask), or in [homebrew-core](https://github.com/Homebrew/homebrew-core)?

**Comment by erbridge** [comment]
I believe it would be in core, but Lime isn't ready to use, so adding a recipe now would be premature.
