### ISSUE TITLE
What happened to @quarnster?

### ISSUE THREAD

**Issue by jeremejevs** [limetext/lime#581]
Does anybody know? His activity just ends abruptly on September 28, 2015.

Sorry about creating an issue about this, but I couldn't find any information or a direct way to contact him, and this is the most relevant place to ask, him being the creator of this project.

@zoli @erbridge @ricochet1k 

**UPDATE:** Mailed him on August 1, no reply as of September 9.

**Comment by zoli** [comment]
I think his email was quarnster@gmail.com.

**Comment by RoelVanNyen** [comment]
Or you could contact him on linkedin (https://www.linkedin.com/in/fredrik-ehnbom-7a43b64/). But I guess the reason you don`t see him around anymore is simply because he does not have time or interest to deal with this anymore.
