### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by hackmaster0110** [limetext/lime#587]
There are no new activities. Is this project dead?

**Comment by JoyceBabu** [comment]
https://github.com/limetext/lime/issues/577
https://github.com/limetext/lime/issues/574
https://github.com/limetext/lime/issues/573

**Comment by itsmattkc** [comment]
It looks like the primary developers no longer have time to work on it and no one's yet managed to fork it and continue it or make something else with the same goal.

**Comment by ankushdas9** [comment]
Afraid so.

**Comment by dessalines** [comment]
damn

**Comment by fearofcode** [comment]
It also appears that the project's domain name has expired.

**Comment by the94air** [comment]
Dear, maintainers. If you guys have a problem, then you should consider https://www.kickstarter.com. With the right advertising, the margin of success pretty huge.

**Comment by cheese-cracker** [comment]
Any fork of this repository which is active?

**Comment by egfx** [comment]
Those looking for an alternative LimeText should look into https://gif.com.ai 

It includes an alternative web interface customized for making GIFs
