### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by ShandoTheKing** [limetext/lime#597]
Seriously this does not look like it's being maintained

**Comment by zoli** [comment]
Pretty much yes.

**Comment by ShandoTheKing** [comment]
Are there any forks of this that's maintained? Because I really want the sublime plugin support

**Comment by zoli** [comment]
None that I'm aware of.

**Comment by ShandoTheKing** [comment]
I guess I'll have to settle for atom then
☹️
